### PR TITLE
Reliability improvements, dynamic buffers, less RAM, simpler example

### PR DESCRIPTION
**Pull request by brainrecall**
I've made the controversial decision to remove the multiple-client support, as that seems to cause several reliability issues and the implementation as it were would only support multiple TCP clients (multiple UDP clients would be expected to use the same exact port? and it was impossible to have one client on UDP and another on TCP). Also, I kept having issues with trying to reconnect after a client disconnects (especially on UDP).

I've also done work to remove all the static buffers, and shrunk down the buffers to reasonable sizes.

I've also overhauled the example to be reduce it to the basics.

There's a bunch of other changes that I can explain, It's a lot of changes so I understand if you don't want to pull these in. Thanks for the work on fixing the RTSP session handling!

Actually, now that I think about it more, multiple clients are quite possible since there are no more static buffers. If we design it more like a traditional web server, once you get a client that connects, spawn them into a separate thread. The thread can allocate their own copies of session and streamer, and each client could do whatever they want, true multi-session. The one trick would be to ensure the "cam" object is locking, so to prevent simultaneous access to the hardware.

Of course that uses more resources, but it doesn't matter much since the ESP32 doesn't have enough performance to feed data to more than one at useful rates.

### CODE REVIEW

**Comment by brainrecall** [comment]
Actually, I would hold off a bit on this. I've been making a bunch of other improvements to the standards conformity, and connection behavior, that is really helping my situation. More details coming.

**Comment by brainrecall** [comment]
I've been hammering on this some more, and I've created a working example with the esp-idf framework rather than arduino. I decided to go straight back to the esp-idf without platform.io since that has the latest direct fixes. I'm cleaning it up some more, and I will have to go back and integrate some changes into the arduino example to get it working, but I have MQTT control of the LED and OTA updates both working.

What I've noticed  is the esp-idf variant is performing very nicely. I've worked the tasking so it handles multiple clients cleanly, very cleanly. I've had two TCP clients and two UDP clients, simultaneously, without issue. The network performance is far better than the arduino settings.

**Comment by Bra1nK** [comment]
I'm trying to compile the arduino example but get "OV2640.cpp:38:18: error: 'CAMERA_GRAB_WHEN_EMPTY' was not declared in this scope" any help to resolve this would be appreciated. I'm compiling for the Al Thinker ESP32-CAM

**Comment by brainrecall** [comment]
Hmm, I'll have to work on this. The Arduino framework is behind the esp-idf camera library. For Arduino, you have to delete the ".grab_mode" lines from OV2640.cpp.

I'll get this fixed, but I'm going to do it on my repo's master branch. I think I'm going to abandon this PR as kdarvis seems to have moved on.

**Pull request closed without merging**
